version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: lpoo-cardgame-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_lpoo_card_game
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
